// This file is autogenerated by build-prefixes.js. DO NOT EDIT!

export interface Targets {
  android?: number,
  chrome?: number,
  edge?: number,
  firefox?: number,
  ie?: number,
  ios_saf?: number,
  opera?: number,
  safari?: number,
  samsung?: number
}
