// generated from https://github.com/sindresorhus/globals/blob/main/globals.json es2015 part
// only init its values while Proxy is supported
export const globals = window.Proxy
  ? [
      'Array',
      'ArrayBuffer',
      'Boolean',
      'constructor',
      'DataView',
      'Date',
      'decodeURI',
      'decodeURIComponent',
      'encodeURI',
      'encodeURIComponent',
      'Error',
      'escape',
      'eval',
      'EvalError',
      'Float32Array',
      'Float64Array',
      'Function',
      'hasOwnProperty',
      'Infinity',
      'Int16Array',
      'Int32Array',
      'Int8Array',
      'isFinite',
      'isNaN',
      'isPrototypeOf',
      'JSON',
      'Map',
      'Math',
      'NaN',
      'Number',
      'Object',
      'parseFloat',
      'parseInt',
      'Promise',
      'propertyIsEnumerable',
      'Proxy',
      'RangeError',
      'ReferenceError',
      'Reflect',
      'RegExp',
      'Set',
      'String',
      'Symbol',
      'SyntaxError',
      'toLocaleString',
      'toString',
      'TypeError',
      'Uint16Array',
      'Uint32Array',
      'Uint8Array',
      'Uint8ClampedArray',
      'undefined',
      'unescape',
      'URIError',
      'valueOf',
      'WeakMap',
      'WeakSet',
    ].filter((p) => /* just keep the available properties in current window context */ p in window)
  : [];
