# git-username [![NPM version](https://img.shields.io/npm/v/git-username.svg?style=flat)](https://www.npmjs.com/package/git-username) [![NPM monthly downloads](https://img.shields.io/npm/dm/git-username.svg?style=flat)](https://npmjs.org/package/git-username)  [![NPM total downloads](https://img.shields.io/npm/dt/git-username.svg?style=flat)](https://npmjs.org/package/git-username) [![Linux Build Status](https://img.shields.io/travis/jonschlinkert/git-username.svg?style=flat&label=Travis)](https://travis-ci.org/jonschlinkert/git-username)

> Get the username from a git remote origin URL.

## Install

Install with [npm](https://www.npmjs.com/):

```sh
$ npm install --save git-username
```

## Usage

```js
var username = require('git-username')();
//=> jonschlinkert
```

Optionally pass a CWD as the second argument:

```js
var username = require('git-username')('foo');
```

## About

### Contributing

Pull requests and stars are always welcome. For bugs and feature requests, [please create an issue](../../issues/new).

### Contributors

| **Commits** | **Contributor** | 
| --- | --- |
| 13 | [jonschlinkert](https://github.com/jonschlinkert) |
| 1 | [jamo](https://github.com/jamo) |

### Building docs

_(This document was generated by [verb-generate-readme](https://github.com/verbose/verb-generate-readme) (a [verb](https://github.com/verbose/verb) generator), please don't edit the readme directly. Any changes to the readme must be made in [.verb.md](.verb.md).)_

To generate the readme and API documentation with [verb](https://github.com/verbose/verb):

```sh
$ npm install -g verb verb-generate-readme && verb
```

### Running tests

Install dev dependencies:

```sh
$ npm install -d && npm test
```

### Author

**Jon Schlinkert**

* [github/jonschlinkert](https://github.com/jonschlinkert)
* [twitter/jonschlinkert](http://twitter.com/jonschlinkert)

### License

Copyright © 2017, [Jon Schlinkert](http://github.com/https://github.com/jonschlinkert).
Released under the [MIT license](LICENSE).

***

_This file was generated by [verb-generate-readme](https://github.com/verbose/verb-generate-readme), v0.2.3, on January 02, 2017._