import '../startup/init.js';
import './preload.js';
import '../core/core.js';
import '../input/mml/mml.js';
import '../output/svg/svg.js';
import '../output/svg/fonts/tex/tex.js';
import '../ui/menu/menu.js';
import '../a11y/assistive-mml/assistive-mml.js';
import '../startup/startup.js';
