name: Emoji Helper

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  emoji:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7
        with:
          script: |
            for (const content of ['+1', 'laugh', 'heart', 'hooray', 'rocket', 'eyes']) {
              await github.rest.reactions.createForRelease({
                ...context.repo,
                release_id: context.payload.release.id,
                content,
              });
            }
