name: Qiankun Github Pages Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          check-latest: true
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"
      - name: Install dependencies
        run: |
          corepack enable
          pnpm install --frozen-lockfile
      - name: Build docs
        run: pnpm run docs:build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
