name: Publish 1.x Version

on:
  push:
    tags:
      - v1.*

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          check-latest: true
          registry-url: "https://registry.npmjs.org"

      - run: corepack enable
      - run: pnpm install
      - run: pnpm publish --tag qiankun1
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
